### ISSUE TITLE
metadata - tools...

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#160]
@byezy Can you call to discuss what these tools are meant to do?? I've finished all the unit test models now.. 

![gg_metadatatools](https://user-images.githubusercontent.com/4453449/28869243-667cf2a0-77bf-11e7-88cc-3f7c95f7a1bc.JPG)

**Comment by byezy** [comment]
first one was your idea... you got some xml file from somewhere and needed the link extracted....

second one I think may have also been abandoned... did you use it in your lls metadata workflow???

**Comment by byezy** [comment]
hey tom, just to get the terminology right before we start interacting with other devs... we are not unit testing our code. unit testing begins at the base code level (actually properly at design time before code is written) and is another beast. I guess we are just "tool testing"... might be why that uni guy got excited when you said we were unit testing... lotsa work n debatable if efficient when applied to scripting code (usually more useful for the underlying scripted code (arc would be unit tested I imagine)... just FYI

**Comment by byezy** [comment]
Get IAR ID from XML:
IT exported xml and we needed to extract a link for you for some reason, the IARID (internal asset register id?)

Import Metadata:
From memory Arc wasn't creating md for newly procced datasets so we wanted to be able to import md from the parent into the child... I think the situation may have changed since we need to review.

**Comment by byezy** [comment]
these are now removed, so closing
